bump up 0.0.19

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,14 +17,17 @@ jobs:
       uses: actions/download-artifact@v2
       with:
         name: version-change-flag
+        path: artifact/
 
     - name: Check for version change flag
       id: check-flag
       run: |
-        if [ -f version_change_flag.txt ]; then
+        if [ -f artifact/version_change_flag.txt ]; then
+          echo "Version change flag found, proceeding with build."
           echo "VERSION_CHANGE_DETECTED=true" >> $GITHUB_ENV
         else
-          echo "VERSION_CHANGE_DETECTED=false" >> $GITHUB_ENV
+          echo "Version change flag not found, skipping build."
+          exit 1
         fi
 
     - if: env.VERSION_CHANGE_DETECTED == 'true'
